### ISSUE TITLE
Generate synthetic sample from trained genralized one shot 

### ISSUE THREAD

**Issue by shiblyg** [thevoidname/Generalized-One-shot-GAN-Adaption#4]
After training G_target.pkl file save in the result directory.
I can also run the inference. But I am wondering how I can create 100 or more single synthetic samples from the trained model.

**Comment by zhangzc21** [comment]
Hi, @shiblyg, for obtaining more syntheses, _e.g._, 100, please manually change  `num = 1`  to  `num = 100`. 
https://github.com/zhangzc21/Generalized-One-shot-GAN-Adaptation/blob/1fad72338ade9e56cf395c730446794f21e6be04/inference.py#L178
